import { test, expect, type Page } from "@playwright/test"
import { workspaceStorageKey } from "../src/utils/storage"

const alpha = Buffer.from("http://127.0.0.1:18042").toString("base64url")
const beta = Buffer.from("http://127.0.0.1:18043").toString("base64url")
async function select(page: Page, name: string) {
  await page.getByRole("button", { name: "Select server", exact: true }).click()
  await page.getByRole("menuitem", { name: new RegExp(name) }).click()
}
test.beforeEach(async ({ page, request }) => {
  for (const port of [18041, 18042, 18043]) await request.post(`http://127.0.0.1:${port}/test/reset`)
  await page.addInitScript(({ alpha, beta }) => {
    if (localStorage.getItem("opencode.connections.v1")) return
    localStorage.setItem("opencode.connections.v1", JSON.stringify([
      { id: alpha, url: "http://127.0.0.1:18042", name: "Alpha", auth: "none" },
      { id: beta, url: "http://127.0.0.1:18043", name: "Beta", auth: "basic", username: "opencode" },
    ]))
    sessionStorage.setItem("opencode.connectionCredentials.v1", JSON.stringify({ [beta]: "beta-secret" }))
  }, { alpha, beta })
})

for (const mobile of [false, true]) {
  test(`home selector is beside bottom controls; project selector stays at top (${mobile ? "mobile" : "desktop"})`, async ({ page }, info) => {
    await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1280, height: 900 })
    await page.goto(`./?server=${alpha}`)
    const selector = page.getByRole("button", { name: "Select server", exact: true })
    await expect(selector).toHaveCount(1)
    const box = (await selector.boundingBox())!
    const terminal = (await page.getByTitle("Terminal (Ctrl+`)", { exact: true }).boundingBox())!
    expect(box.x).toBeLessThan(64)
    expect(box.y).toBeGreaterThan(page.viewportSize()!.height - 180)
    expect(terminal.y - box.y).toBeGreaterThan(0)
    expect(terminal.y - box.y).toBeLessThan(60)
    await selector.click()
    await expect(page.getByRole("menuitem", { name: /Beta/ })).toBeInViewport()
    await page.screenshot({ path: info.outputPath("home-bottom-selector.png"), fullPage: true })
    await page.keyboard.press("Escape")
    await page.goto(`./L3dvcmtzcGFjZQ/session/ses_shared?server=${alpha}`)
    await expect(selector).toHaveCount(1)
    expect((await selector.boundingBox())!.y).toBeLessThan(110)
    await page.screenshot({ path: info.outputPath("project-top-selector.png"), fullPage: true })
    if (!mobile) {
      await page.getByTitle("Collapse Sidebar (Ctrl+B)", { exact: true }).click()
      await expect(selector).toHaveCount(1)
      expect((await selector.boundingBox())!.x).toBeLessThan(64)
      expect((await selector.boundingBox())!.y).toBeLessThan(110)
      await page.screenshot({ path: info.outputPath("project-collapsed-top-selector.png"), fullPage: true })
    }
  })
}

test("settings switching retains provider, MCP and appearance tabs and returns to target workspace", async ({ page, request }, info) => {
  await page.goto(`./L3RhcmdldA/session?new=beta-draft&server=${beta}`)
  await select(page, "Alpha")
  await page.getByRole("button", { name: "Open Project", exact: true }).last().click()
  await page.getByRole("textbox", { name: "Search directories", exact: true }).fill("/workspace")
  await page.getByRole("button", { name: "Open path", exact: true }).click()
  await page.getByTitle("Settings", { exact: true }).click()
  await expect(page.getByText("Alpha Provider", { exact: true })).toBeVisible()
  await select(page, "Beta")
  await expect(page).toHaveURL(/L3RhcmdldA\/settings\?server=.*$/)
  await expect(page.getByText("Beta Provider", { exact: true })).toBeVisible()
  await expect(page.getByText("Alpha Provider", { exact: true })).toHaveCount(0)
  await page.screenshot({ path: info.outputPath("settings-beta-providers.png"), fullPage: true })
  await page.getByRole("button", { name: /MCP Servers/ }).click()
  await expect(page.getByText("Beta MCP detail", { exact: true })).toBeVisible()
  await select(page, "Alpha")
  await expect(page).toHaveURL(/settings\?server=.*#mcp$/)
  await expect(page.getByText("Alpha MCP detail", { exact: true })).toBeVisible()
  await expect(page.getByText("Beta MCP detail", { exact: true })).toHaveCount(0)
  await select(page, "Beta")
  await expect(page.getByText("Beta MCP detail", { exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("settings-beta-mcp.png"), fullPage: true })
  await page.getByRole("button", { name: /Appearance/ }).click()
  await select(page, "Alpha")
  await expect(page).toHaveURL(/#appearance$/)
  await expect(page.getByRole("heading", { name: "Appearance", exact: true })).toBeVisible()
  await select(page, "Beta")
  await page.getByRole("button", { name: "Back to workspace", exact: true }).click()
  await expect(page).toHaveURL(/L3RhcmdldA\/session\?new=beta-draft&server=/)
  for (const [port, directory, authorization] of [[18042, "/workspace", null], [18043, "/target", `Basic ${Buffer.from("opencode:beta-secret").toString("base64")}`]] as const) {
    const requests = await (await request.get(`http://127.0.0.1:${port}/test/requests`)).json()
    const scoped = requests.filter((row: { path: string }) => ["/provider", "/mcp"].includes(row.path))
    expect(scoped.length).toBeGreaterThan(0)
    expect(scoped.some((row: { directory: string }) => row.directory === directory)).toBe(true)
    expect(scoped.every((row: { directory: string | null; authorization: string | null }) => (!row.directory || row.directory === directory) && row.authorization === authorization)).toBe(true)
  }
})

test("remote MCP removal is unavailable in settings and the session dialog", async ({ page, request }) => {
  for (const id of [alpha, "local"]) {
    const query = id === "local" ? "" : `?server=${id}`
    await page.goto(`./L3dvcmtzcGFjZQ/settings${query}#mcp`)
    const remove = page.getByRole("button", { name: "Remove shared MCP server", exact: true })
    if (id === alpha) {
      await expect(remove).toBeDisabled()
      await expect(remove).toHaveAttribute("title", /disconnect instead/)
      await expect(page.getByRole("switch", { name: "Toggle shared connection", exact: true })).toBeEnabled()
    } else await expect(remove).toBeEnabled()
    await page.goto(`./L3dvcmtzcGFjZQ/session/ses_shared${query}`)
    await page.getByRole("button", { name: "MCP Servers", exact: true }).click()
    if (id === alpha) {
      await expect(remove).toBeDisabled()
      await expect(remove).toHaveAttribute("title", /disconnect instead/)
    } else await expect(remove).toBeEnabled()
  }
  for (const port of [18041, 18042])
    expect(await (await request.get(`http://127.0.0.1:${port}/test/writes`)).json()).toEqual([])
})

test("late provider and MCP responses cannot replace the selected settings server", async ({ page, request }) => {
  await request.post("http://127.0.0.1:18042/test/hold?path=/provider")
  await request.post("http://127.0.0.1:18042/test/hold?path=/mcp")
  await page.goto(`./settings?server=${alpha}#providers`)
  await expect.poll(async () => {
    const rows: { path: string }[] = await (await request.get("http://127.0.0.1:18042/test/requests")).json()
    return ["/provider", "/mcp"].every(path => rows.some(row => row.path === path))
  }).toBe(true)
  await select(page, "Beta")
  await expect(page.getByText("Beta Provider", { exact: true })).toBeVisible()
  const late = Promise.all(["/provider", "/mcp"].map(path => page.waitForResponse(response => response.url().includes(`/api/remote/${alpha}${path}`) && new URL(response.url()).pathname.endsWith(path))))
  await request.post("http://127.0.0.1:18042/test/release?path=/provider")
  await request.post("http://127.0.0.1:18042/test/release?path=/mcp")
  await late
  await expect(page.getByText("Alpha Provider", { exact: true })).toHaveCount(0)
  await page.getByRole("button", { name: /MCP Servers/ }).click()
  await expect(page.getByText("Beta MCP detail", { exact: true })).toBeVisible()
  await expect(page.getByText("Alpha MCP detail", { exact: true })).toHaveCount(0)
  await page.getByRole("button", { name: "Back to workspace", exact: true }).click()
  await expect(page).toHaveURL(url => !/\/(settings|session)/.test(url.pathname) && url.searchParams.get("server") === beta)
})

test("top sidebar selection restores isolated same-ID sessions and drafts", async ({ page, request }, info) => {
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  const prompt = page.getByPlaceholder("Type a message... (Tab to switch agent, / for commands)")
  await page.goto(`./L3dvcmtzcGFjZQ/session/ses_shared?server=${alpha}`)
  await expect(page.getByRole("heading", { name: "Alpha session", exact: true })).toBeVisible()
  await prompt.fill("Alpha draft only")
  await expect(page.getByRole("navigation", { name: "Open sessions" })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Choose project" })).toHaveCount(0)
  const selector = page.getByRole("button", { name: "Select server", exact: true })
  const box = await selector.boundingBox()
   expect(box!.x).toBeLessThan(100)
   expect(box!.y).toBeLessThan(60)
  await selector.focus()
  await page.keyboard.press("Enter")
  await expect(page.getByRole("menuitem", { name: /Alpha/ })).toHaveAttribute("aria-current", "true")
  await expect(page.getByRole("menu").getByRole("textbox")).toHaveCount(0)
  await page.screenshot({ path: info.outputPath("server-selector.png"), fullPage: true })
  await page.keyboard.press("Escape")
  await expect(selector).toBeFocused()
  await select(page, "Beta")
  await expect(page).toHaveURL(url => url.searchParams.get("server") === beta)
  await expect(page.getByRole("heading", { name: "Alpha session", exact: true })).toHaveCount(0)
  await page.getByRole("button", { name: "Open Project", exact: true }).last().click()
  await page.getByRole("textbox", { name: "Search directories", exact: true }).fill("/workspace")
  await page.getByRole("button", { name: "Open path", exact: true }).click()
  await page.getByRole("link", { name: "Beta session", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Beta session", exact: true })).toBeVisible()
  await expect(prompt).toHaveValue("")
  await prompt.fill("Beta draft only")
  const frames: string[] = []
  page.on("websocket", ws => ws.on("framereceived", frame => frames.push(String(frame.payload))))
  await page.getByRole("button", { name: "Toggle Terminal", exact: true }).click()
  await expect.poll(() => frames.join("")).toContain("Beta terminal")
  await select(page, "Alpha")
  await expect(page.getByRole("heading", { name: "Alpha session", exact: true })).toBeVisible()
  await expect(prompt).toHaveValue("Alpha draft only")
  await expect(page.getByText("Beta terminal", { exact: true })).toHaveCount(0)
  await expect.poll(async () => (await request.get("http://127.0.0.1:18043/test/streams")).json()).toBe(1)
  await select(page, "Beta")
  await expect(prompt).toHaveValue("Beta draft only")
  await page.reload()
  await expect(page.getByRole("heading", { name: "Beta session", exact: true })).toBeVisible()
  await page.getByRole("option", { name: /Select session Beta session/ }).hover()
  await page.getByRole("button", { name: "More session options", exact: true }).first().click()
  await page.getByRole("menuitem", { name: "Rename", exact: true }).click()
  await page.getByRole("textbox", { name: "Session title", exact: true }).fill("Beta renamed")
  await page.getByRole("textbox", { name: "Session title", exact: true }).press("Enter")
  await expect(page.getByRole("heading", { name: "Beta renamed", exact: true })).toBeVisible()
  expect(await (await request.get("http://127.0.0.1:18042/test/writes")).json()).not.toContain("Beta renamed")
  expect(await page.evaluate(() => localStorage.getItem("opencode.connections.v1"))).not.toContain("beta-secret")
  await page.screenshot({ path: info.outputPath("restored-navigation.png"), fullPage: true })
  expect(errors).toEqual([])
})

test("local drafts reuse empties, retain text and promote in place", async ({ page, request }, info) => {
  const prompt = page.getByPlaceholder("Type a message... (Tab to switch agent, / for commands)")
  await page.goto(`./L3dvcmtzcGFjZQ/session/ses_shared?server=${alpha}`)
  await page.getByRole("button", { name: "New Session", exact: true }).click()
  const route = page.url()
  const key = new URL(route).searchParams.get("new")!
  const entry = page.locator(`[data-draft-entry="${key}"]`)
  await expect(entry.getByRole("button", { name: "New session Draft", exact: true })).toHaveAttribute("aria-current", "page")
  await page.getByRole("button", { name: "New Session", exact: true }).dblclick()
  expect(page.url()).toBe(route)
  await expect(page.locator("[data-draft-entry]")).toHaveCount(1)
  expect(await (await request.get("http://127.0.0.1:18042/test/writes")).json()).toEqual([])
  await prompt.fill("Keep my draft")
  await page.getByRole("button", { name: "New Session", exact: true }).click()
  await expect(page.locator("[data-draft-entry]")).toHaveCount(2)
  await page.goBack()
  await expect(prompt).toHaveValue("Keep my draft")
  await page.goForward()
  await expect(prompt).toHaveValue("")
  await entry.getByRole("button", { name: "New session Draft", exact: true }).click()
  await expect(prompt).toHaveValue("Keep my draft")
  await select(page, "Beta")
  await page.getByRole("button", { name: "Open Project", exact: true }).last().click()
  await page.getByRole("textbox", { name: "Search directories", exact: true }).fill("/workspace")
  await page.getByRole("button", { name: "Open path", exact: true }).click()
  await prompt.fill("Beta local draft")
  await select(page, "Alpha")
  await expect(prompt).toHaveValue("Keep my draft")
  await select(page, "Beta")
  await expect(prompt).toHaveValue("Beta local draft")
  await select(page, "Alpha")
  await expect(prompt).toHaveValue("Keep my draft")
  await expect(page.getByRole("button", { name: "Model: Alpha Model", exact: true })).toBeVisible()
  await page.getByTitle("Home", { exact: true }).click()
  await page.getByTitle("workspace", { exact: true }).click()
  await expect(page).toHaveURL(route)
  await expect(prompt).toHaveValue("Keep my draft")
  await expect(page.getByRole("button", { name: "Model: Alpha Model", exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("sidebar-local-drafts.png"), fullPage: true })
  const before = await entry.boundingBox()
  await prompt.press("Enter")
  await expect(page).toHaveURL(/session\/ses_alpha_1/)
  await expect(entry.getByRole("link", { name: "Alpha new session", exact: true })).toBeVisible()
  await expect(page.getByRole("heading", { name: "Alpha new session", exact: true })).toBeVisible()
  await expect(page.getByText("Failed to load this session. Check your connection and try again.", { exact: true })).toHaveCount(0)
  expect((await entry.boundingBox())!.y).toBe(before!.y)
  await expect(page.getByRole("link", { name: "Alpha new session", exact: true })).toHaveCount(1)
  expect(await (await request.get("http://127.0.0.1:18042/test/writes")).json()).toEqual(["create", "prompt"])
  await page.screenshot({ path: info.outputPath("sidebar-promoted-draft.png"), fullPage: true })
  await page.getByRole("button", { name: "New session Draft", exact: true }).click()
  await page.getByRole("button", { name: "Remove draft", exact: true }).click()
  await expect(page.getByRole("button", { name: "Remove draft", exact: true })).toHaveCount(0)
  await expect(page).toHaveURL(/session\/ses_alpha_1/)
})

test("pending creation sends once and preserves further typing during promotion", async ({ page, request }) => {
  await page.goto(`./L3dvcmtzcGFjZQ/session?new=pending&server=${alpha}`)
  await expect(page.getByRole("button", { name: "Model: Alpha Model", exact: true })).toBeVisible()
  let release!: () => void
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route(`**/api/remote/${alpha}/session`, async route => {
    if (route.request().method() === "POST") await gate
    await route.continue()
  })
  const prompt = page.getByPlaceholder("Type a message... (Tab to switch agent, / for commands)")
  await prompt.fill("First message")
  await prompt.press("Enter")
  await expect(prompt).toHaveValue("")
  await prompt.fill("Still typing")
  await prompt.press("Enter")
  release()
  await expect(page).toHaveURL(/session\/ses_alpha_1/)
  await expect(prompt).toHaveValue("Still typing")
  await expect.poll(async () => (await request.get("http://127.0.0.1:18042/test/writes")).json()).toEqual(["create", "prompt"])
})

test("failed creation retains the draft and mobile selector stays at the top", async ({ page }, info) => {
  await page.goto(`./L3dvcmtzcGFjZQ/session?new=failure&server=${alpha}`)
  const prompt = page.getByPlaceholder("Type a message... (Tab to switch agent, / for commands)")
  await expect(page.getByRole("button", { name: "Model: Alpha Model", exact: true })).toBeVisible()
  await page.route(`**/api/remote/${alpha}/session`, route => route.request().method() === "POST" ? route.fulfill({ status: 503, body: "Unavailable" }) : route.continue())
  await prompt.fill("Retain on failure")
  await prompt.press("Enter")
  await expect(page.getByText(/Failed to send the first message/)).toBeVisible()
  await expect(prompt).toHaveValue("Retain on failure")
  await expect(page.locator('[data-draft-entry="failure"]')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  const selector = page.getByRole("button", { name: "Select server", exact: true })
  await expect(selector).toHaveAttribute("title", /Alpha.*18042/)
  await expect(selector).toBeVisible()
  await expect.poll(async () => (await page.getByRole("navigation", { name: "Session list", includeHidden: true }).boundingBox())?.width ?? 0).toBe(0)
  expect((await selector.boundingBox())!.y).toBeLessThan(110)
  await selector.click()
  await expect(page.getByRole("menuitem", { name: /Alpha/ })).toHaveAttribute("aria-current", "true")
  await page.screenshot({ path: info.outputPath("mobile-top-selector.png"), fullPage: true })
})

test("Settings edits retain active server and all authentication modes", async ({ page }) => {
  await page.goto(`./L3dvcmtzcGFjZQ/settings?server=${alpha}#servers`)
  await page.getByRole("button", { name: "Edit Beta", exact: true }).click()
  const url = page.url()
  await expect(page.getByLabel("Authentication", { exact: true }).locator("option")).toHaveText(["None", "Browser-Session", "Username and password", "Bearer token"])
  await page.getByRole("button", { name: "Save connection", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Manage servers", exact: true })).toBeVisible()
  expect(page.url()).toBe(url)
  await select(page, "Beta")
  await expect(page).toHaveURL(url => url.searchParams.get("server") === beta && url.pathname.endsWith("/settings") && url.hash === "#servers")
  await select(page, "Alpha")
  await expect(page).toHaveURL(url => url.searchParams.get("server") === alpha && url.pathname.includes("settings"))
})

test("providers follow server switches on the same settings route", async ({ page, request }, info) => {
  await page.goto(`./settings?server=${alpha}`)
  await expect(page.getByText("Alpha Provider", { exact: true })).toBeVisible()
  await request.post("http://127.0.0.1:18043/test/hold?path=/provider")
  await select(page, "Beta")
  await expect(page).toHaveURL(url => url.pathname.endsWith("/settings") && url.searchParams.get("server") === beta)
  await expect(page.getByText("Alpha Provider", { exact: true })).toHaveCount(0)
  await expect(page.getByText("Providers for Beta.", { exact: false })).toBeVisible()
  await request.post("http://127.0.0.1:18043/test/release?path=/provider")
  await expect(page.getByText("Beta Provider", { exact: true })).toBeVisible()
  await select(page, "Alpha")
  await expect(page.getByText("Alpha Provider", { exact: true })).toBeVisible()
  await expect(page.getByText("Beta Provider", { exact: true })).toHaveCount(0)
  await select(page, "Beta")
  await expect(page.getByText("Beta Provider", { exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("server-providers.png"), fullPage: true })
})

test("late OAuth authorization cannot start a callback from detached settings", async ({ page, request }) => {
  const path = "/provider/mock/oauth/authorize"
  await request.post(`http://127.0.0.1:18042/test/hold?path=${path}`)
  await page.goto(`./settings?server=${alpha}`)
  await page.getByRole("button", { name: "Reconfigure Alpha Provider", exact: true }).click()
  await page.getByRole("button", { name: "Alpha device login", exact: true }).click()
  await expect.poll(async () => (await (await request.get("http://127.0.0.1:18042/test/requests")).json()).some((r: { path: string }) => r.path === path)).toBe(true)
  await select(page, "Beta")
  await request.post(`http://127.0.0.1:18042/test/release?path=${path}`)
  await page.waitForTimeout(500)
  expect(await (await request.get("http://127.0.0.1:18042/test/writes")).json()).toEqual([])
  expect(await (await request.get("http://127.0.0.1:18043/test/writes")).json()).toEqual([])
})

test("provider edits and credential removal target only their server", async ({ page, request }, info) => {
  await page.goto(`./L3dvcmtzcGFjZQ/settings?server=${alpha}`)
  await page.getByRole("button", { name: "Reconfigure Alpha Provider", exact: true }).click()
  await page.getByPlaceholder("Enter your API key...").fill("alpha-provider-secret")
  await select(page, "Beta")
  await page.getByTitle("Settings", { exact: true }).click()
  await expect(page.getByPlaceholder("Enter your API key...")).toHaveCount(0)
  await page.getByRole("button", { name: "Reconfigure Beta Provider", exact: true }).click()
  await expect(page.getByPlaceholder("Enter your API key...")).toHaveValue("")
  await expect(page.getByText("Beta API key", { exact: true })).toBeVisible()
  await expect(page.getByText("Alpha API key", { exact: true })).toHaveCount(0)
  await page.getByPlaceholder("Enter your API key...").fill("beta-provider-secret")
  await page.getByRole("button", { name: "Save", exact: true }).click()
  await expect(page.getByText("Connected to mock!", { exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Disconnect Beta Provider", exact: true }).click()
  await page.getByRole("button", { name: "Disconnect", exact: true }).click()
  await expect(page.getByText("Disconnected Beta Provider.", { exact: true })).toBeVisible()
  expect(await (await request.get("http://127.0.0.1:18042/test/writes")).json()).toEqual([])
  expect(await (await request.get("http://127.0.0.1:18041/test/writes")).json()).toEqual([])
  expect(await (await request.get("http://127.0.0.1:18043/test/writes")).json()).toEqual(["auth:PUT", "dispose", "auth:DELETE", "dispose"])
  const requests = await (await request.get("http://127.0.0.1:18043/test/requests")).json()
  expect(requests.filter((r: { path: string }) => r.path === "/auth/mock").every((r: { directory: string | null; cookie: boolean }) => !r.directory && !r.cookie)).toBe(true)
  await select(page, "Alpha")
  await expect(page.getByText("Alpha Provider", { exact: true })).toBeVisible()
  await expect(page.getByPlaceholder("Enter your API key...")).toHaveCount(0)
  await page.screenshot({ path: info.outputPath("isolated-provider-settings.png"), fullPage: true })
})

test("in-flight OAuth completion stays on its origin without detached refetch writes", async ({ page, request }) => {
  const path = "/provider/mock/oauth/callback"
  await request.post(`http://127.0.0.1:18042/test/hold?path=${path}`)
  await page.route("https://provider.example/**", route => route.fulfill({ body: "Fixture authorization" }))
  await page.goto(`./settings?server=${alpha}`)
  await page.getByRole("button", { name: "Reconfigure Alpha Provider", exact: true }).click()
  await page.getByRole("button", { name: "Alpha device login", exact: true }).click()
  await expect.poll(async () => (await (await request.get("http://127.0.0.1:18042/test/requests")).json()).some((r: { path: string }) => r.path === path)).toBe(true)
  await select(page, "Beta")
  await page.getByTitle("Settings", { exact: true }).click()
  await request.post(`http://127.0.0.1:18042/test/release?path=${path}`)
  await expect.poll(async () => (await (await request.get("http://127.0.0.1:18042/test/writes")).json())).toEqual(["oauth:callback"])
  await expect(page.getByText("Beta Provider", { exact: true })).toBeVisible()
  await expect(page.getByText(/Connected to Alpha/)).toHaveCount(0)
  expect(await (await request.get("http://127.0.0.1:18043/test/writes")).json()).toEqual([])
})

test("in-flight API key writes cannot dispose or refresh a detached server scope", async ({ page, request }) => {
  const path = "/auth/mock"
  await request.post(`http://127.0.0.1:18042/test/hold?path=${path}`)
  await page.goto(`./L3dvcmtzcGFjZQ/settings?server=${alpha}`)
  await page.getByRole("button", { name: "Reconfigure Alpha Provider", exact: true }).click()
  await page.getByPlaceholder("Enter your API key...").fill("fixture-alpha-key")
  await page.getByRole("button", { name: "Save", exact: true }).click()
  await expect.poll(async () => (await (await request.get("http://127.0.0.1:18042/test/requests")).json()).some((r: { path: string }) => r.path === path)).toBe(true)
  await select(page, "Beta")
  await request.post(`http://127.0.0.1:18042/test/release?path=${path}`)
  await page.waitForTimeout(300)
  expect(await (await request.get("http://127.0.0.1:18042/test/writes")).json()).toEqual(["auth:PUT"])
  expect(await (await request.get("http://127.0.0.1:18043/test/writes")).json()).toEqual([])
})

test("active OAuth completion refetches only the selected server's connected providers", async ({ page, request }) => {
  await request.delete("http://127.0.0.1:18043/auth/mock", { headers: { authorization: `Basic ${Buffer.from("opencode:beta-secret").toString("base64")}` } })
  await page.route("https://provider.example/**", route => route.fulfill({ body: "Fixture authorization" }))
  await page.goto(`./settings?server=${beta}`)
  await expect(page.getByRole("button", { name: "Reconfigure Beta Provider", exact: true })).toHaveCount(0)
  await page.getByRole("button", { name: "Beta Provider 2 models", exact: true }).click()
  await page.getByRole("button", { name: "Beta device login", exact: true }).click()
  await expect(page.getByText("Connected to Beta Provider!", { exact: true })).toBeVisible()
  await expect(page.getByRole("button", { name: "Reconfigure Beta Provider", exact: true })).toBeVisible()
  expect(await (await request.get("http://127.0.0.1:18043/test/writes")).json()).toEqual(["auth:DELETE", "oauth:callback", "dispose"])
  expect(await (await request.get("http://127.0.0.1:18042/test/writes")).json()).toEqual([])
  expect(await (await request.get("http://127.0.0.1:18041/test/writes")).json()).toEqual([])
})

test("late provider bootstrap and remote errors never display another server's providers", async ({ page, request }) => {
  await request.post("http://127.0.0.1:18042/test/hold?path=/provider")
  await page.goto(`./settings?server=${alpha}`)
  await expect.poll(async () => (await (await request.get("http://127.0.0.1:18042/test/requests")).json()).some((r: { path: string }) => r.path === "/provider")).toBe(true)
  await select(page, "Beta")
  await page.getByTitle("Settings", { exact: true }).click()
  await expect(page.getByText("Beta Provider", { exact: true })).toBeVisible()
  await request.post("http://127.0.0.1:18042/test/release?path=/provider")
  await page.waitForTimeout(300)
  await expect(page.getByText("Alpha Provider", { exact: true })).toHaveCount(0)
  await page.route(`**/api/remote/${beta}/provider`, route => route.fulfill({ status: 503, body: "Unavailable" }))
  await page.reload()
  await expect(page.getByRole("heading", { name: "Providers", exact: true })).toBeVisible()
  await expect(page.getByText("Local Provider", { exact: true })).toHaveCount(0)
  await expect(page.getByText("Alpha Provider", { exact: true })).toHaveCount(0)
  await expect(page.getByText("Beta Provider", { exact: true })).toHaveCount(0)
})

test("saved model choices survive loading and stay server scoped in the picker", async ({ page, request }, info) => {
  const key = workspaceStorageKey(alpha, "/workspace", "modelsByAgent")
  await page.addInitScript(({ key }) => {
    if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify({ build: { providerID: "mock", modelID: "alternate" } }))
  }, { key })
  await request.post("http://127.0.0.1:18042/test/hold?path=/provider")
  await page.goto(`./L3dvcmtzcGFjZQ/session?server=${alpha}`)
  await page.waitForTimeout(200)
  expect(JSON.parse((await page.evaluate(key => localStorage.getItem(key), key))!).build.modelID).toBe("alternate")
  await request.post("http://127.0.0.1:18042/test/release?path=/provider")
  await expect(page.getByRole("button", { name: "Model: Alpha Alternate", exact: true })).toBeVisible()
  await select(page, "Beta")
  await page.getByRole("button", { name: "Open Project", exact: true }).last().click()
  await page.getByRole("textbox", { name: "Search directories", exact: true }).fill("/workspace")
  await page.getByRole("button", { name: "Open path", exact: true }).click()
  await page.getByRole("button", { name: "Model: Beta Model", exact: true }).click()
  await expect(page.getByText("Beta Alternate", { exact: true })).toBeVisible()
  await expect(page.getByText("Alpha Alternate", { exact: true })).toHaveCount(0)
  await page.screenshot({ path: info.outputPath("server-model-picker.png"), fullPage: true })
  await page.keyboard.press("Escape")
  await select(page, "Alpha")
  await expect(page.getByRole("button", { name: "Model: Alpha Alternate", exact: true })).toBeVisible()
})

test("missing credentials and removed connections recover without local fallback", async ({ page }) => {
  await page.goto(`./L3dvcmtzcGFjZQ/session/ses_shared?server=${beta}`)
  await page.evaluate(() => sessionStorage.removeItem("opencode.connectionCredentials.v1"))
  await page.reload()
  await expect(page.getByRole("status")).toContainText("Authentication required")
  await expect(page.getByRole("heading", { name: "Local session" })).toHaveCount(0)
  await page.getByRole("button", { name: "Server settings", exact: true }).click()
  await page.getByRole("button", { name: "Edit Beta", exact: true }).click()
  await page.getByLabel("Password", { exact: true }).fill("wrong-password")
  await page.getByRole("button", { name: "Save connection", exact: true }).click()
  await expect(page.getByRole("alert")).toContainText("HTTP 401")
  await page.getByLabel("Password", { exact: true }).fill("beta-secret")
  await page.getByRole("button", { name: "Save connection", exact: true }).click()
  await page.getByRole("button", { name: "Back to workspace", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Beta session", exact: true })).toBeVisible()
  await page.getByTitle("Settings", { exact: true }).click()
  await page.getByRole("button", { name: "Servers", exact: true }).click()
  await page.getByRole("button", { name: "Remove Beta", exact: true }).click()
  await expect(page).toHaveURL(url => url.pathname.endsWith("/settings/servers") && url.searchParams.get("server") === beta)
  await expect(page.getByRole("button", { name: "Select server", exact: true })).toHaveAttribute("title", "Server unavailable")
  await expect(page.getByRole("heading", { name: "Manage servers", exact: true })).toBeVisible()
  expect(await page.evaluate(() => sessionStorage.getItem("opencode.connectionCredentials.v1"))).not.toContain("beta-secret")
  await select(page, "Local server")
  await expect(page).toHaveURL(url => !url.searchParams.has("server"))
})
